/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Just For Us - Community Forum API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary List all forum categories
 */
export const ListCategoriesResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "description": zod.string(),
  "color": zod.string(),
  "threadCount": zod.number()
})
export const ListCategoriesResponse = zod.array(ListCategoriesResponseItem)


/**
 * @summary List forum threads
 */
export const ListThreadsQueryParams = zod.object({
  "categoryId": zod.coerce.number().nullish(),
  "search": zod.coerce.string().nullish(),
  "limit": zod.coerce.number().nullish(),
  "offset": zod.coerce.number().nullish()
})

export const ListThreadsResponseItem = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "body": zod.string(),
  "authorName": zod.string(),
  "isAnonymous": zod.boolean(),
  "categoryId": zod.number(),
  "categoryName": zod.string(),
  "categoryColor": zod.string(),
  "replyCount": zod.number(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})
export const ListThreadsResponse = zod.array(ListThreadsResponseItem)


/**
 * @summary Create a new thread
 */
export const createThreadBodyTitleMin = 3;

export const createThreadBodyBodyMin = 10;



export const CreateThreadBody = zod.object({
  "title": zod.string().min(createThreadBodyTitleMin),
  "body": zod.string().min(createThreadBodyBodyMin),
  "authorName": zod.string(),
  "isAnonymous": zod.boolean(),
  "categoryId": zod.number()
})

export const CreateThreadResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "body": zod.string(),
  "authorName": zod.string(),
  "isAnonymous": zod.boolean(),
  "categoryId": zod.number(),
  "categoryName": zod.string(),
  "categoryColor": zod.string(),
  "replyCount": zod.number(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})


/**
 * @summary Get a single thread
 */
export const GetThreadParams = zod.object({
  "id": zod.coerce.number()
})

export const GetThreadResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "body": zod.string(),
  "authorName": zod.string(),
  "isAnonymous": zod.boolean(),
  "categoryId": zod.number(),
  "categoryName": zod.string(),
  "categoryColor": zod.string(),
  "replyCount": zod.number(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})


/**
 * @summary Delete a thread
 */
export const DeleteThreadParams = zod.object({
  "id": zod.coerce.number()
})

export const DeleteThreadResponse = zod.void()


/**
 * @summary List replies for a thread
 */
export const ListRepliesParams = zod.object({
  "id": zod.coerce.number()
})

export const ListRepliesResponseItem = zod.object({
  "id": zod.number(),
  "threadId": zod.number(),
  "body": zod.string(),
  "authorName": zod.string(),
  "isAnonymous": zod.boolean(),
  "createdAt": zod.string()
})
export const ListRepliesResponse = zod.array(ListRepliesResponseItem)


/**
 * @summary Add a reply to a thread
 */
export const CreateReplyParams = zod.object({
  "id": zod.coerce.number()
})

export const createReplyBodyBodyMin = 3;



export const CreateReplyBody = zod.object({
  "body": zod.string().min(createReplyBodyBodyMin),
  "authorName": zod.string(),
  "isAnonymous": zod.boolean()
})

export const CreateReplyResponse = zod.object({
  "id": zod.number(),
  "threadId": zod.number(),
  "body": zod.string(),
  "authorName": zod.string(),
  "isAnonymous": zod.boolean(),
  "createdAt": zod.string()
})


/**
 * @summary Get community overview statistics
 */
export const GetStatsResponse = zod.object({
  "totalThreads": zod.number(),
  "totalReplies": zod.number(),
  "totalCategories": zod.number(),
  "recentActivity": zod.number()
})


/**
 * @summary Get recent forum activity
 */
export const GetRecentThreadsResponseItem = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "body": zod.string(),
  "authorName": zod.string(),
  "isAnonymous": zod.boolean(),
  "categoryId": zod.number(),
  "categoryName": zod.string(),
  "categoryColor": zod.string(),
  "replyCount": zod.number(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})
export const GetRecentThreadsResponse = zod.array(GetRecentThreadsResponseItem)


