/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Just For Us - Community Forum API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Category,
  CommunityStats,
  HealthStatus,
  ListThreadsParams,
  Reply,
  ReplyInput,
  Thread,
  ThreadInput
} from './api.schemas';

import { customFetch } from '../custom-fetch';
import type { ErrorType , BodyType } from '../custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getHealthCheckUrl = () => {




  return `/api/healthz`
}

/**
 * Returns server health status
 * @summary Health check
 */
export const healthCheck = async ( options?: RequestInit): Promise<HealthStatus> => {

  return customFetch<HealthStatus>(getHealthCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthCheckQueryKey = () => {
    return [
    `/api/healthz`
    ] as const;
    }


export const getHealthCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({ signal }) => healthCheck({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>
export type HealthCheckQueryError = ErrorType<unknown>


/**
 * @summary Health check
 */

export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthCheckQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getListCategoriesUrl = () => {




  return `/api/categories`
}

/**
 * @summary List all forum categories
 */
export const listCategories = async ( options?: RequestInit): Promise<Category[]> => {

  return customFetch<Category[]>(getListCategoriesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListCategoriesQueryKey = () => {
    return [
    `/api/categories`
    ] as const;
    }


export const getListCategoriesQueryOptions = <TData = Awaited<ReturnType<typeof listCategories>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listCategories>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCategoriesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCategories>>> = ({ signal }) => listCategories({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listCategories>>, TError, TData> & { queryKey: QueryKey }
}

export type ListCategoriesQueryResult = NonNullable<Awaited<ReturnType<typeof listCategories>>>
export type ListCategoriesQueryError = ErrorType<unknown>


/**
 * @summary List all forum categories
 */

export function useListCategories<TData = Awaited<ReturnType<typeof listCategories>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listCategories>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListCategoriesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getListThreadsUrl = (params?: ListThreadsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/threads?${stringifiedParams}` : `/api/threads`
}

/**
 * @summary List forum threads
 */
export const listThreads = async (params?: ListThreadsParams, options?: RequestInit): Promise<Thread[]> => {

  return customFetch<Thread[]>(getListThreadsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListThreadsQueryKey = (params?: ListThreadsParams,) => {
    return [
    `/api/threads`, ...(params ? [params] : [])
    ] as const;
    }


export const getListThreadsQueryOptions = <TData = Awaited<ReturnType<typeof listThreads>>, TError = ErrorType<unknown>>(params?: ListThreadsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listThreads>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListThreadsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listThreads>>> = ({ signal }) => listThreads(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listThreads>>, TError, TData> & { queryKey: QueryKey }
}

export type ListThreadsQueryResult = NonNullable<Awaited<ReturnType<typeof listThreads>>>
export type ListThreadsQueryError = ErrorType<unknown>


/**
 * @summary List forum threads
 */

export function useListThreads<TData = Awaited<ReturnType<typeof listThreads>>, TError = ErrorType<unknown>>(
 params?: ListThreadsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listThreads>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListThreadsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getCreateThreadUrl = () => {




  return `/api/threads`
}

/**
 * @summary Create a new thread
 */
export const createThread = async (threadInput: ThreadInput, options?: RequestInit): Promise<Thread> => {

  return customFetch<Thread>(getCreateThreadUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(threadInput)
  }
);}




export const getCreateThreadMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createThread>>, TError,{data: BodyType<ThreadInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createThread>>, TError,{data: BodyType<ThreadInput>}, TContext> => {

const mutationKey = ['createThread'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createThread>>, {data: BodyType<ThreadInput>}> = (props) => {
          const {data} = props ?? {};

          return  createThread(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateThreadMutationResult = NonNullable<Awaited<ReturnType<typeof createThread>>>
    export type CreateThreadMutationBody = BodyType<ThreadInput>
    export type CreateThreadMutationError = ErrorType<unknown>

    /**
 * @summary Create a new thread
 */
export const useCreateThread = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createThread>>, TError,{data: BodyType<ThreadInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createThread>>,
        TError,
        {data: BodyType<ThreadInput>},
        TContext
      > => {
      return useMutation(getCreateThreadMutationOptions(options));
    }

export const getGetThreadUrl = (id: number,) => {




  return `/api/threads/${id}`
}

/**
 * @summary Get a single thread
 */
export const getThread = async (id: number, options?: RequestInit): Promise<Thread> => {

  return customFetch<Thread>(getGetThreadUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetThreadQueryKey = (id: number,) => {
    return [
    `/api/threads/${id}`
    ] as const;
    }


export const getGetThreadQueryOptions = <TData = Awaited<ReturnType<typeof getThread>>, TError = ErrorType<void>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getThread>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetThreadQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getThread>>> = ({ signal }) => getThread(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getThread>>, TError, TData> & { queryKey: QueryKey }
}

export type GetThreadQueryResult = NonNullable<Awaited<ReturnType<typeof getThread>>>
export type GetThreadQueryError = ErrorType<void>


/**
 * @summary Get a single thread
 */

export function useGetThread<TData = Awaited<ReturnType<typeof getThread>>, TError = ErrorType<void>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getThread>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetThreadQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getDeleteThreadUrl = (id: number,) => {




  return `/api/threads/${id}`
}

/**
 * @summary Delete a thread
 */
export const deleteThread = async (id: number, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getDeleteThreadUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteThreadMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteThread>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteThread>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteThread'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteThread>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteThread(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteThreadMutationResult = NonNullable<Awaited<ReturnType<typeof deleteThread>>>

    export type DeleteThreadMutationError = ErrorType<unknown>

    /**
 * @summary Delete a thread
 */
export const useDeleteThread = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteThread>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteThread>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteThreadMutationOptions(options));
    }

export const getListRepliesUrl = (id: number,) => {




  return `/api/threads/${id}/replies`
}

/**
 * @summary List replies for a thread
 */
export const listReplies = async (id: number, options?: RequestInit): Promise<Reply[]> => {

  return customFetch<Reply[]>(getListRepliesUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListRepliesQueryKey = (id: number,) => {
    return [
    `/api/threads/${id}/replies`
    ] as const;
    }


export const getListRepliesQueryOptions = <TData = Awaited<ReturnType<typeof listReplies>>, TError = ErrorType<unknown>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listReplies>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListRepliesQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listReplies>>> = ({ signal }) => listReplies(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listReplies>>, TError, TData> & { queryKey: QueryKey }
}

export type ListRepliesQueryResult = NonNullable<Awaited<ReturnType<typeof listReplies>>>
export type ListRepliesQueryError = ErrorType<unknown>


/**
 * @summary List replies for a thread
 */

export function useListReplies<TData = Awaited<ReturnType<typeof listReplies>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listReplies>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListRepliesQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getCreateReplyUrl = (id: number,) => {




  return `/api/threads/${id}/replies`
}

/**
 * @summary Add a reply to a thread
 */
export const createReply = async (id: number,
    replyInput: ReplyInput, options?: RequestInit): Promise<Reply> => {

  return customFetch<Reply>(getCreateReplyUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(replyInput)
  }
);}




export const getCreateReplyMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createReply>>, TError,{id: number;data: BodyType<ReplyInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createReply>>, TError,{id: number;data: BodyType<ReplyInput>}, TContext> => {

const mutationKey = ['createReply'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createReply>>, {id: number;data: BodyType<ReplyInput>}> = (props) => {
          const {id,data} = props ?? {};

          return  createReply(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateReplyMutationResult = NonNullable<Awaited<ReturnType<typeof createReply>>>
    export type CreateReplyMutationBody = BodyType<ReplyInput>
    export type CreateReplyMutationError = ErrorType<unknown>

    /**
 * @summary Add a reply to a thread
 */
export const useCreateReply = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createReply>>, TError,{id: number;data: BodyType<ReplyInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createReply>>,
        TError,
        {id: number;data: BodyType<ReplyInput>},
        TContext
      > => {
      return useMutation(getCreateReplyMutationOptions(options));
    }

export const getGetStatsUrl = () => {




  return `/api/stats/overview`
}

/**
 * @summary Get community overview statistics
 */
export const getStats = async ( options?: RequestInit): Promise<CommunityStats> => {

  return customFetch<CommunityStats>(getGetStatsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetStatsQueryKey = () => {
    return [
    `/api/stats/overview`
    ] as const;
    }


export const getGetStatsQueryOptions = <TData = Awaited<ReturnType<typeof getStats>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStatsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStats>>> = ({ signal }) => getStats({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData> & { queryKey: QueryKey }
}

export type GetStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getStats>>>
export type GetStatsQueryError = ErrorType<unknown>


/**
 * @summary Get community overview statistics
 */

export function useGetStats<TData = Awaited<ReturnType<typeof getStats>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetStatsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetRecentThreadsUrl = () => {




  return `/api/threads/recent`
}

/**
 * @summary Get recent forum activity
 */
export const getRecentThreads = async ( options?: RequestInit): Promise<Thread[]> => {

  return customFetch<Thread[]>(getGetRecentThreadsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetRecentThreadsQueryKey = () => {
    return [
    `/api/threads/recent`
    ] as const;
    }


export const getGetRecentThreadsQueryOptions = <TData = Awaited<ReturnType<typeof getRecentThreads>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRecentThreads>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRecentThreadsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRecentThreads>>> = ({ signal }) => getRecentThreads({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRecentThreads>>, TError, TData> & { queryKey: QueryKey }
}

export type GetRecentThreadsQueryResult = NonNullable<Awaited<ReturnType<typeof getRecentThreads>>>
export type GetRecentThreadsQueryError = ErrorType<unknown>


/**
 * @summary Get recent forum activity
 */

export function useGetRecentThreads<TData = Awaited<ReturnType<typeof getRecentThreads>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRecentThreads>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetRecentThreadsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







