/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Just For Us - Community Forum API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface Category {
  id: number;
  name: string;
  description: string;
  color: string;
  threadCount: number;
}

export interface Thread {
  id: number;
  title: string;
  body: string;
  authorName: string;
  isAnonymous: boolean;
  categoryId: number;
  categoryName: string;
  categoryColor: string;
  replyCount: number;
  createdAt: string;
  updatedAt: string;
}

export interface ThreadInput {
  /** @minLength 3 */
  title: string;
  /** @minLength 10 */
  body: string;
  authorName: string;
  isAnonymous: boolean;
  categoryId: number;
}

export interface Reply {
  id: number;
  threadId: number;
  body: string;
  authorName: string;
  isAnonymous: boolean;
  createdAt: string;
}

export interface ReplyInput {
  /** @minLength 3 */
  body: string;
  authorName: string;
  isAnonymous: boolean;
}

export interface CommunityStats {
  totalThreads: number;
  totalReplies: number;
  totalCategories: number;
  recentActivity: number;
}

export type ListThreadsParams = {
/**
 * @nullable
 */
categoryId?: number | null;
/**
 * @nullable
 */
search?: string | null;
/**
 * @nullable
 */
limit?: number | null;
/**
 * @nullable
 */
offset?: number | null;
};

