/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Just For Us - Community Forum API
 * OpenAPI spec version: 0.1.0
 */

export interface CommunityStats {
  totalThreads: number;
  totalReplies: number;
  totalCategories: number;
  recentActivity: number;
}
