/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Just For Us - Community Forum API
 * OpenAPI spec version: 0.1.0
 */

export interface Reply {
  id: number;
  threadId: number;
  body: string;
  authorName: string;
  isAnonymous: boolean;
  createdAt: string;
}
