/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Just For Us - Community Forum API
 * OpenAPI spec version: 0.1.0
 */

export interface ThreadInput {
  /** @minLength 3 */
  title: string;
  /** @minLength 10 */
  body: string;
  authorName: string;
  isAnonymous: boolean;
  categoryId: number;
}
