/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Just For Us - Community Forum API
 * OpenAPI spec version: 0.1.0
 */

export interface Thread {
  id: number;
  title: string;
  body: string;
  authorName: string;
  isAnonymous: boolean;
  categoryId: number;
  categoryName: string;
  categoryColor: string;
  replyCount: number;
  createdAt: string;
  updatedAt: string;
}
